package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme tokens
val SmartYellow = Color(0xFF6750A4)
val SmartYellowDark = Color(0xFF21005D)
val SmartYellowLight = Color(0xFFEADDFF)
val SmartBlack = Color(0xFF1D1B20)
val SmartBlackDark = Color(0xFFFEF7FF)
val SmartBlackPaper = Color(0xFFF3EDF7)
val SmartBlackCard = Color(0xFFFFFFFF)
val SmartGrayLight = Color(0xFFF8F5FB)
val SmartGrayMedium = Color(0xFF49454F)
val SmartGrayDark = Color(0xFFE7E0EC)
val SmartSuccess = Color(0xFF10B981)
val SmartError = Color(0xFFDC2626)
val SmartOrange = Color(0xFFF59E0B)

val SleekPurple = Color(0xFF6750A4)
val SleekPurpleContainer = Color(0xFFEADDFF)
val SleekDeepPurple = Color(0xFF21005D)
val SleekOutline = Color(0xFFE7E0EC)
val SleekBadgeBlue = Color(0xFFD3E3FD)
val SleekBadgeBlueText = Color(0xFF041E49)
val SleekBadgeYellow = Color(0xFFFEEFC3)
val SleekBadgeYellowText = Color(0xFF442E00)
val SleekBadgeGreen = Color(0xFFC4EED0)
val SleekBadgeGreenText = Color(0xFF072711)

// Dark scheme tokens (missing before -- this was the white-on-white cause)
val SmartPrimaryDark = Color(0xFFD0BCFF)
val SmartOnPrimaryDark = Color(0xFF381E72)
val SmartPrimaryContainerDark = Color(0xFF4F378B)
val SmartOnPrimaryContainerDark = Color(0xFFEADDFF)
val SmartBackgroundDark = Color(0xFF141218)
val SmartOnBackgroundDark = Color(0xFFE6E0E9)
val SmartSurfaceDark = Color(0xFF1D1B20)
val SmartOnSurfaceDark = Color(0xFFE6E0E9)
val SmartSurfaceVariantDark = Color(0xFF49454F)
val SmartOnSurfaceVariantDark = Color(0xFFCAC4D0)
val SmartOutlineDark = Color(0xFF938F99)
